spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-204.railway.app:7747/railway
    username: postgres
    password: JmB6Hs7ztNe2c8bzG6Ak
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: carpooling2023_
  application:
      name: microservice-route
  cloud:
    vault:
      token: hvs.u9Wzar894whiuqpPK57NOJiq
      scheme: http
      host: localhost
      port: 8200
  config:
    import: vault://
server:
  port: 8082
processor:
    queue:
      route:
        request: route.request-route.qu
        request-routing-key: request-route.rk
        response-create: route.response-route.created.qu
        create-routing-key: response-route.created.rk
    exchange:
      route: route.ex
google:
  maps:
    api:
      key: 7u7
hola: ${api-key}
