spring:
  datasource:
    url: ${url-database}
    username: ${user-database}
    password: ${password-database}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${rabbit-host}
    port: 5671
    username: ${rabbit-user}
    password: ${rabbit-password}
    virtual-host: ${rabbit-user}
    ssl:
      enabled: true
    application:
      name: microservice-route
  cloud:
    vault:
      uri: http://18.116.86.155:8200
      token: UWU
      connection-timeout: 5000
      read-timeout: 15000
  config:
    import: vault://cubbyhole/microservice-route
logging:
  level:
    org:
      springframework:
        cloud:
          vault: DEBUG
server:
  port: 8082
processor:
    queue:
      route:
        request: route.request-route.qu
        save-route: route.save-route.qu
        request-routing-key: request-route.rk
        response-create: route.response-route.created.qu
        create-routing-key: response-route.created.rk
        save-routing-key: save-route.save.rk
        response-get-activate-route: route.get.activate-route.qu
        get-activate-routing-key: response-route.get-activate.rk
    exchange:
      route: route.ex
google:
  maps:
    api:
      key: ${google-api-key}
