spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-204.railway.app:7747/railway
    username: postgres
    password: BScWjyfvqmHY5QTAmOCr
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: carpooling2023_
carpooling:
    queue:
      save-route: route.queue.save
      routing-key: route.queue.rk
    exchange:
      route: route.ex
google:
  maps:
    api:
      key: 7u7
