spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-204.railway.app:7747/railway
    username: postgres
    password: BScWjyfvqmHY5QTAmOCr
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
